= Non sense
:published_at: 2008-02-18
:hp-tags: nonsense

E de repente ele percebeu que estava num maldito círculo vicioso. A felicidade deste despertar se misturava com a decepção da consciência de que não havia conseguido. E por mais que ele tentasse não conseguia abandonar. Se sentiu a pessoa mais infeliz do mundo. Sabia que não poderia permanecer ali. Se martirizou e praguejou os criadores daquele paradoxo. Havia algum criador? Não estaria ele preguejando a si mesmo? Sabia que tinha que fugir dalí. Mas sabia que o que quer que fosse o seguiria infinitamente não importando a distância. O mundo tinha a circunferência de uma laranja. Sabia que alí não havia espaço para chapeus nem cobras que comem elefantes… Fugir era fácil e nem adiantava. A vida o engoliria da mesma forma e o vomitaria neste ciclo errante. Sua única estratégia seria amalgamar seu peito com a mais dura das ligas metálicas ao preço de perder-se por completo. Mas sabia que não existia escolha. O ciclo o egoliria sempre… Na mesma intensidade. Com o tempo enfraqueceria.. Talvez o bastante para tornar rotina e não conseguir mais amalgamar-se com nada. E novamente perder-se-ia por completo.
Teria coragem?