= O Desafio dos 5 dolares! – O que você faria com cinco dolares e duas horas?
:published_at: 2015-01-04
:uri-tina: http://www.psychologytoday.com/experts/tina-seelig
:uri-psy: http://www.psychologytoday.com/blog/creativityrulz/200908/the-5-challenge

Traduzido por mim, e retirado com a autorização da autora, {uri-tina}[Tina Seelig], {uri-psy}[daqui].

O que você faria para ganhar dinheiro, se tudo o que tivesse fosse cinco dólares e duas horas? Esta é a tarefa que eu dei aos alunos em uma das minhas aulas na Universidade de Stanford, como parte da Stanford Technology Ventures Program … Cada uma de quatorze equipes receberam um envelope com cinco dólares de “capital semente” (seed funding) e foi dito que poderiam gastar quanto tempo quisessem com planejamento. No entanto, uma vez que abrissem o envelope, teriam duas horas para gerar o máximo de dinheiro possível. Eu dei-lhes a partir de quarta-feira à tarde até domingo à noite para completar a tarefa. Então, na noite de domingo, cada equipe teve que me enviar um slide descrevendo o que tinham feito, e na segunda-feira à tarde cada equipe teve três minutos para apresentar o seu projecto para a classe. Eles foram incentivados a ser empreendedor, identificando oportunidades, desafiando suposições, alavancando os recursos limitados que eles tinham, e serem criativos.

O que você faria se lhe fosse dada a este desafio? Quando eu fiz essa pergunta para a maioria dos grupos, alguém geralmente grita: “Vá para Las Vegas”, ou “Comprar um bilhete de loteria.” Este recebe uma grande risada. Essas pessoas levaria um risco significativa em troca de uma pequena chance de ganhar uma grande recompensa. A próxima sugestão mais comum é a criação de um posto de lavagem de carro ou limonada, usando os cinco dólares para comprar os materiais de partida. Esta é uma boa opção para os interessados em ganhar alguns dólares extras ao gastar dinheiro em duas horas. Mas a maioria dos meus alunos, eventualmente, encontrou uma maneira de mover-se muito para além das respostas padrão. Eles levaram a sério o desafio de questionar hipóteses tradicionais – expondo uma riqueza de possibilidades – a fim de criar o maior valor possível.

Como eles fizeram isso? Aqui vai uma dica: as equipes que fizeram a maior parte do dinheiro não usou os cinco dólares em tudo. Eles perceberam que, focar no dinheiro, na verdade, enquadrou o problema de maneira muito restrita. Eles entenderam que cinco dólares é essencialmente nada e decidiram reinterpretar o problema de forma mais ampla: O que podemos fazer para ganhar dinheiro se começarmos com absolutamente nada? Eles desenvolveram suas habilidades de observação, aproveitado seus talentos, e abriram suas criatividades para identificar os problemas em seu centro – problemas que experimentaram ou notaram que outros experimentam – problemas que poderiam ter visto antes, mas nunca tinham parado para resolver. Estes problemas eram irritantes, mas não necessariamente na vanguarda da mente de ninguém. Ao desenterrar esses problemas e, em seguida, trabalhar para resolvê-los, as equipes vencedoras trouxe mais de US $ 600, sendo o retorno médio sobre o investimento de cinco dólar era de 4.000 por cento! Se você levar em conta que muitas das equipes não usaram os fundos em tudo, então seus retornos financeiros eram infinitas.

Então, o que eles fizeram? Todas as equipes eram notavelmente inventiva. Um grupo identificado um problema comum em muitas cidades universitárias – filas frustrantes e longas nos restaurantes populares na noite de sábado. A equipe decidiu ajudar aquelas pessoas que não querem esperar na fila. Eles agruparam e fizeram reservas em vários restaurantes. Como os tempos para as suas reservas se aproximou, eles venderam cada reserva por até vinte dólares para clientes que estavam felizes para evitar uma longa espera. À medida que a noite avançava, eles fizeram várias observações interessantes. Em primeiro lugar, eles perceberam que as estudantes do sexo feminino eram melhores em vender as reservas do que os estudantes do sexo masculino, provavelmente porque os clientes estavam mais confortável de ser abordado pelas jovens. Eles ajustaram seu plano para que os estudantes do sexo masculino corressem pela cidade para fazer reservas em restaurantes diferentes, enquanto as estudantes do sexo feminino vendiam nesses locais. Aprenderam também que toda a operação funcionou melhor em restaurantes que usam pagers que vibram para alertar os clientes quando a sua mesa está pronta. Trocar pagers físicos fez com que os clientes se sintissem como se estivessem recebendo algo tangível para seu dinheiro. Eles estavam mais confortáveis em entregar seu dinheiro em troca do novo pager. Isto teve um bônus adicional – as equipes poderiam, então, vender o pager recém-adquirido enquanto o tempo de reserva mais tarde se aproximava.

Outra equipe tomou uma abordagem ainda mais simples. Eles montaram um estande na frente da associação de estudantes, onde eles ofereceram para medir a pressão do pneu da bicicleta de forma gratuita. Se os pneus precisasse ser enchido, eles seriam enchidos por um dólar. No início, eles acharam que estavam se aproveitando de seus colegas, que poderia facilmente ir a um posto de gasolina próximo e ter seus pneus cheios. Mas, depois de seus primeiros clientes, os alunos perceberam que os ciclistas eram incrivelmente grato. Mesmo que os ciclistas pudessem ter seus pneus cheios de graça nas proximidades, e a tarefa foi fácil de realizar, eles logo perceberam que estavam prestando um serviço conveniente e valioso. Na verdade, no meio do período de duas horas, a equipe parou de pedir um pagamento específico e pediu doações em seu lugar. Sua renda aumentou. Eles fizeram muito mais quando os seus clientes foram levados a dar reciprocidade para um serviço gratuito que quando solicitado a pagar um preço fixo. Para esta equipe, bem como para a equipe que fazia reservas em restaurantes, a experimentação ao longo do caminho valeu a pena. O processo iterativo, onde pequenas alterações são feitas em resposta ao feedback dos clientes, lhes permitiu optimizar a sua estratégia em tempo real.

Cada um desses projetos trouxe algumas centenas de dólares, e os seus colegas de classe ficaram devidamente impressionados. No entanto, a equipe que gerou o maior lucro olhou para os recursos à sua disposição através de lentes completamente diferentes, e fez US $ 650. Estes estudantes determinaram que o bem mais valioso que eles tinham nem eram os cinco dólares, nem as duas horas. Em vez disso, sua visão era que seu recurso mais precioso era o seu tempo de apresentação de três minutos na segunda-feira. Eles decidiram vendê-lo para uma empresa que queria recrutar os estudantes na classe. A equipe criou um “comercial” de três minutos para essa empresa e mostrou para os alunos durante o tempo que teria apresentado o que tinham feito na semana anterior. Este foi brilhante. Eles reconheceram que tinham um ativo fabulosamente valioso que os outros nem perceberam – só esperando para ser extraído.