= O Suicídio Mais Bizarro de 1994
:published_at: 2015-01-04

Este texto foi traduzido por mim mas retirado de http://www.quora.com/What-are-the-best-short-stories

Em 23 de março de 1994, um médico legista examinou o corpo de Ronald Opus e concluiu que ele morreu devido a um tiro de espingarda na cabeça. O falecido tinha saltado do alto de um prédio de dez andares com a intenção de cometer suicídio (ele deixou uma nota de suicídio confirmando sua intenção).

Quando ele caiu após o nono andar, a sua vida foi interrompida por um tiro de espingarda por uma janela, que o matou instantaneamente. Nem o atirador nem o falecido estava ciente de que uma rede de segurança havia sido instalada no nível do oitavo andar, para proteger alguns lavadores de janelas e que Opus não teria sido capaz de consumar seu suicídio de qualquer maneira por causa disso. ”
“Normalmente, “Dr. Mills continuou, “uma pessoa que se propõe a cometer suicídio em última análise, bem-sucedido, mesmo que o mecanismo pode não ser o que ele pretendia. Isso Opus foi baleado no caminho para a morte certa nove andares abaixo provavelmente não teria mudado seu modo de morte por suicídio ao homicídio. Mas o fato de que sua intenção suicida não teria sido bem sucedida fec com que o médico legista considerasse que ele tinha um homicídio em suas mãos. “O quarto do nono andar de onde o tiro de espingarda saiu era ocupado por um homem idoso e sua esposa. Eles estavam discutindo e ele estava ameaçando-a com a espingarda. Ele estava tão chateado que, quando ele puxou o gatilho, ele perdeu completamente sua esposa e a bala passou pela janela acertando Opus surpreendentemente.

“Quando alguém tenta matar a vítima A mas acidentalmente mata a vítima B na tentativa, é culpado do homicídio de B. Quando confrontado com esta acusação, o velho e sua esposa foram ambos inflexível que nem sabia que a arma estava carregada. O velho disse que era seu hábito de longa data para ameaçar sua esposa com a espingarda descarregada. Portanto ele não tinha a intenção de matá-la, o assassinato de Opus parecia ser um acidente. Ou seja, a arma tinha sido carregada acidentalmente.

“Contudo a investigação descobriu uma testemunha que vira o filho do casal carregar a espingarda aproximadamente seis semanas antes do incidente fatal. Foi descoberto que a senhora havia cortado a mesada do filho e este, sabendo que a propensão de seu pai para usar a espingarda ameaçadoramente, carregou a arma com a expectativa de que seu pai matasse sua mãe. o caso passa a ser uma das assassinato por parte do filho para a morte de Ronald Opus.
Houve uma reviravolta requintado. “Investigações posteriores revelaram que o filho [Ronald Opus] tinha-se tornado cada vez mais desanimado com o fracasso de sua tentativa de projetar o assassinato de sua mãe. Isso o levou a pular do prédio de dez andares em 23 de março, apenas para ser morto por um tiro de espingarda através de uma janela do nono andar.
“O médico legista encerrou o caso como suicídio.”